const APPLY={

   
    APPLY_LOADING_REQUEST : "APPLY_LOADING_REQUEST",
    APPLY_LOADING_FAILURE : "APPLY_LOADING_FAILURE",
    APPLY_LOADING_SUCCESS : "APPLY_LOADING_SUCCESS",

    
    
    APPLY_BOARD_USER_REQUEST : "APPLY_BOARD_USER_REQUEST",
    APPLY_BOARD_USER_FAILURE : "APPLY_BOARD_USER_FAILURE",
    APPLY_BOARD_USER_SUCCESS : "APPLY_BOARD_USER_SUCCESS",

   
     APPLY_UPLOADING_REQUEST : "APPLY_UPLOADING_REQUEST",
     APPLY_UPLOADING_FAILURE : "APPLY_UPLOADING_FAILURE",
     APPLY_UPLOADING_SUCCESS : "APPLY_UPLOADING_SUCCESS",


     APPLY_CONTRACT_REQUEST : "APPLY_CONTRACT_REQUEST",
     APPLY_CONTRACT_FAILURE : "APPLY_CONTRACT_FAILURE",
     APPLY_CONTRACT_SUCCESS : "APPLY_CONTRACT_SUCCESS",

   
     REVIEW_UPLOADING_REQUEST : "REVIEW_UPLOADING_REQUEST",
     REVIEW_UPLOADING_FAILURE : "REVIEW_UPLOADING_FAILURE",
     REVIEW_UPLOADING_SUCCESS : "REVIEW_UPLOADING_SUCCESS",


     REVIEW_PROFILE_REQUEST : "REVIEW_PROFILE_REQUEST",
     REVIEW_PROFILE_FAILURE : "REVIEW_PROFILE_FAILURE",
     REVIEW_PROFILE_SUCCESS : "REVIEW_PROFILE_SUCCESS",

 
     REVIEW_DETAIL_REQUEST : "REVIEW_DETAIL_REQUEST",
     REVIEW_DETAIL_FAILURE : "REVIEW_DETAIL_FAILURE",
     REVIEW_DETAIL_SUCCESS : "REVIEW_DETAIL_SUCCESS",

    APPLY_DELETE_REQUEST : "APPLY_DELETE_REQUEST",
    APPLY_DELETE_FAILURE : "APPLY_DELETE_FAILURE",
    APPLY_DELETE_SUCCESS : "APPLY_DELETE_SUCCESS",

     APPLY_DETAIL_REQUEST : "APPLY_DETAIL_REQUEST",
     APPLY_DETAIL_FAILURE : "APPLY_DETAIL_FAILURE",
     APPLY_DETAIL_SUCCESS : "APPLY_DETAIL_SUCCESS",
   
    
    
    };
    export default APPLY;    
        
    
    
    
    
    
    
    