const MYPAGE={

   
     MYPAGE_BOOKMARK_REQUEST : "MYPAGE_BOOKMARK_REQUEST",
     MYPAGE_BOOKMARK_FAILURE : "MYPAGE_BOOKMARK_FAILURE",
     MYPAGE_BOOKMARK_SUCCESS : "MYPAGE_BOOKMARK_SUCCESS",
 
     MYPAGE_APPLY_REQUEST : " MYPAGE_APPLY_REQUEST",
     MYPAGE_APPLY_FAILURE : " MYPAGE_APPLY_FAILURE",
     MYPAGE_APPLY_SUCCESS : " MYPAGE_APPLY_SUCCESS",


     MYPAGE_BOARD_REQUEST : " MYPAGE_BOARD_REQUEST",
     MYPAGE_BOARD_FAILURE : " MYPAGE_BOARD_FAILURE",
     MYPAGE_BOARD_SUCCESS : " MYPAGE_BOARD_SUCCESS",
    


    MYPAGE_REPORT_REQUEST : " MYPAGE_REPORT_REQUEST",
    MYPAGE_REPORT_FAILURE : " MYPAGE_REPORT_FAILURE",
    MYPAGE_REPORT_SUCCESS : " MYPAGE_REPORT_SUCCESS",
   
    



    };
    export default MYPAGE;    
        
    
    
    
    
    
    
    