const POST={


 POST_LOADING_REQUEST : "POST_LOADING_REQUEST",
 POST_LOADING_FAILURE : "POST_LOADING_FAILURE",
 POST_LOADING_SUCCESS : "POST_LOADING_SUCCESS",


 POST_UPLOADING_REQUEST : "POST_UPLOADING_REQUEST",
 POST_UPLOADING_FAILURE : "POST_UPLOADING_FAILURE",
 POST_UPLOADING_SUCCESS : "POST_UPLOADING_SUCCESS",


POST_DETAIL_LOADING_REQUEST : "POST_DETAIL_LOADING_REQUEST",
POST_DETAIL_LOADING_FAILURE : "POST_DETAIL_LOADING_FAILURE",
POST_DETAIL_LOADING_SUCCESS : "POST_DETAIL_LOADING_SUCCESS",


POST_EDIT_REQUEST : "POST_EDIT_REQUEST",
POST_EDIT_FAILURE : "POST_EDIT_FAILURE",
POST_EDIT_SUCCESS : "POST_EDIT_SUCCESS",

POST_DELETE_REQUEST : "POST_DELETE_REQUEST",
POST_DELETE_FAILURE : "POST_DELETE_FAILURE",
POST_DELETE_SUCCESS : "POST_DELETE_SUCCESS",


 TAG_LOADING_REQUEST : "TAG_LOADING_REQUEST",
 TAG_LOADING_FAILURE : "TAG_LOADING_FAILURE",
 TAG_LOADING_SUCCESS : "TAG_LOADING_SUCCESS",


 TAG_SEARCH_REQUEST : "TAG_SEARCH_REQUEST",
 TAG_SEARCH_FAILURE : "TAG_SEARCH_FAILURE",
 TAG_SEARCH_SUCCESS : "TAG_SEARCH_SUCCESS",


 BOOKMARK_LOADING_REQUEST : "BOOKMARK_LOADING_REQUEST",
 BOOKMARK_LOADING_FAILURE : "BOOKMARK_LOADING_FAILURE",
 BOOKMARK_LOADING_SUCCESS : "BOOKMARK_LOADING_SUCCESS",

 BOOKMARK_UPLOADING_REQUEST : "BOOKMARK_UPLOADING_REQUEST",
 BOOKMARK_UPLOADING_FAILURE : "BOOKMARK_UPLOADING_FAILURE",
 BOOKMARK_UPLOADING_SUCCESS : "BOOKMARK_UPLOADING_SUCCESS",


  BOOKMARK_DELETE_REQUEST : "BOOKMARK_DELETE_REQUEST",
  BOOKMARK_DELETE_FAILURE : "BOOKMARK_DELETE_FAILURE",
  BOOKMARK_DELETE_SUCCESS : "BOOKMARK_DELETE_SUCCESS",
 


};
export default POST;    
    






