const PROFILE={


    
     PROFILE_CHECK_REQUEST : "PROFILE_CHECK_REQUEST",
     PROFILE_CHECK_FAILURE : "PROFILE_CHECK_FAILURE",
     PROFILE_CHECK_SUCCESS : "PROFILE_CHECK_SUCCESS",


    PROFILE_ISOPEN_REQUEST : "PROFILE_ISOPEN_REQUEST",
    PROFILE_ISOPEN_SUCCESS : "PROFILE_ISOPEN_SUCCESS",
    PROFILE_ISOPEN_FAILURE : "PROFILE_ISOPEN_FAILURE",

 
     PROFILE_LOADING_REQUEST : "PROFILE_LOADING_REQUEST",
     PROFILE_LOADING_FAILURE : "PROFILE_LOADING_FAILURE",
     PROFILE_LOADING_SUCCESS : "PROFILE_LOADING_SUCCESS",
    

     PROFILE_UPLOADING_REQUEST : "PROFILE_UPLOADING_REQUEST",
     PROFILE_UPLOADING_FAILURE : "PROFILE_UPLOADING_FAILURE",
     PROFILE_UPLOADING_SUCCESS : "PROFILE_UPLOADING_SUCCESS",
    
    

    PROFILE_DETAIL_LOADING_REQUEST : "PROFILE_DETAIL_LOADING_REQUEST",
    PROFILE_DETAIL_LOADING_FAILURE : "PROFILE_DETAIL_LOADING_FAILURE",
    PROFILE_DETAIL_LOADING_SUCCESS : "PROFILE_DETAIL_LOADING_SUCCESS",
    

    PROFILE_EDIT_REQUEST : "PROFILE_EDIT_REQUEST",
    PROFILE_EDIT_SUCCESS : "PROFILE_EDIT_SUCCESS",
    PROFILE_EDIT_FAILURE : "PROFILE_EDIT_FAILURE",
    
  
     PROFILE_DELETE_REQUEST : "PROFILE_DELETE_REQUEST",
     PROFILE_DELETE_SUCCESS : "PROFILE_DELETE_SUCCESS",
     PROFILE_DELETE_FAILURE : "PROFILE_DELETE_FAILURE",
  
    
    };
    export default PROFILE;    
        
    
    
    
    
    
    
    