const REPORT={

   
    REPORT_LOADING_REQUEST : "REPORT_LOADING_REQUEST",
    REPORT_LOADING_FAILURE : "REPORT_LOADING_FAILURE",
    REPORT_LOADING_SUCCESS : "REPORT_LOADING_SUCCESS",
    

     REPORT_UPLOADING_REQUEST : "REPORT_UPLOADING_REQUEST",
     REPORT_UPLOADING_FAILURE : "REPORT_UPLOADING_FAILURE",
     REPORT_UPLOADING_SUCCESS : "REPORT_UPLOADING_SUCCESS",
    
    
     REPORT_DETAIL_REQUEST : "REPORT_DETAIL_REQUEST",
     REPORT_DETAIL_FAILURE : "REPORT_DETAIL_FAILURE",
     REPORT_DETAIL_SUCCESS : "REPORT_DETAIL_SUCCESS",
    
    };
    export default REPORT;    
        
    
    
    
    
    
    
    