const USER={


  USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE",


  USER_ACCOUNT_REQUEST : "USER_ACCOUNT_REQUEST",
  USER_ACCOUNT_SUCCESS : "USER_ACCOUNT_SUCCESS",
  USER_ACCOUNT_FAILURE : "USER_ACCOUNT_FAILURE",



  USER_LOGOUT_REQUEST : "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE : "USER_LOGOUT_FAILURE",

 
  USER_EDIT_REQUEST : "USER_EDIT_REQUEST",
  USER_EDIT_SUCCESS : "USER_EDIT_SUCCESS",
  USER_EDIT_FAILURE : "USER_EDIT_FAILURE",


  USER_LOADING_REQUEST : "USER_LOADING_REQUEST",
  USER_LOADING_SUCCESS : "USER_LOADING_SUCCESS",
  USER_LOADING_FAILURE : "USER_LOADING_FAILURE",


   LOGIN_LOADING_REQUEST : "LOGIN_LOADING_REQUEST",
   LOGIN_LOADING_SUCCESS : "LOGIN_LOADING_SUCCESS",
   LOGIN_LOADING_FAILURE : "LOGIN_LOADING_FAILURE",



  USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE",


   USER_DELETE_REQUEST : "USER_DELETE_REQUEST",
   USER_DELETE_SUCCESS : "USER_DELETE_SUCCESS",
   USER_DELETE_FAILURE : "USER_DELETE_FAILURE",


  CLEAR_ERROR_REQUEST : "CLEAR_ERROR_REQUEST",
  CLEAR_ERROR_SUCCESS : "CLEAR_ERROR_SUCCESS",
  CLEAR_ERROR_FAILURE : "CLEAR_ERROR_FAILURE",

};


export default USER;